import type { ImageMetadata } from "astro";

// ============================================================================
// CONFIGURATION TYPES
// ============================================================================

/**
 * Navigation item in the header navigation
 */
export interface NavItem {
    href: string;
    label: string;
    special?: boolean;
    blank?: boolean;
}

/**
 * Social media link configuration
 */
export interface SocialObjects {
    name: string;
    href: string;
    active: boolean;
    linkTitle?: string;
}

/**
 * Site-level configuration
 */
export interface SiteConfig {
    website: string;
    author: string;
    repo: string;
    branch?: string;
    title: string;
    description: string;
    image?: unknown;
    imageAlt?: string;
    twitterHandle?: string;
    starCountThreshold?: number;
    enableLayoutWidthToggle?: boolean;
    enableGitHubButton?: boolean;
}

// ============================================================================
// NAVIGATION TYPES
// ============================================================================

/**
 * Sidebar entry representing a single documentation page
 */
export interface Entry {
    slug: string;
    label?: string;
    icon?: string;
    hidden?: boolean;
}

/**
 * Sidebar group containing entries and subgroups
 */
export interface Group {
    id: string;
    label: string;
    icon?: string;
    path?: string;
    tab?: boolean;
    autoGenerated?: boolean;
    groups?: Group[];
    entries?: Entry[];
}

/**
 * Sidebar configuration containing groups
 */
export interface Sidebar {
    groups: Group[];
}

// ============================================================================
// LAYOUT COMPONENT TYPES
// ============================================================================

/**
 * Props for HeadSEO component
 */
export interface HeadSEOProps {
    title: string;
    description: string;
    image: string | ImageMetadata;
    imageAlt: string;
    contentType: string;
    noIndex?: boolean;
}

/**
 * Props for BaseLayout component
 */
export interface BaseLayoutProps extends Partial<HeadSEOProps> {
    fullWidth?: boolean;
}

/**
 * Props for DocsLayout component
 */
export interface DocsLayoutProps extends Partial<HeadSEOProps> {
    currentSlug: string;
    headings?: Heading[];
}

// ============================================================================
// CORE COMPONENT TYPES
// ============================================================================

/**
 * Props for DocIcon component - displays icon with fallback to document icon
 */
export interface DocIconProps {
    name?: string;
    class?: string;
    [key: string]: unknown;
}

/**
 * Props for ThemeToggle component - no props required
 */
export interface ThemeToggleProps {
    // No props required
}

/**
 * Props for LayoutWidthToggle component - no props required
 */
export interface LayoutWidthToggleProps {
    // No props required
}

/**
 * Props for HeaderGithubButton component - no props required
 */
export interface HeaderGithubButtonProps {
    // No props required
}

/**
 * Props for HeaderLogo component - no props required
 */
export interface HeaderLogoProps {
    // No props required
}

/**
 * Props for HeaderNav component
 */
export interface HeaderNavProps {
    navItems: NavItem[];
}

/**
 * Props for Header component - no props required
 */
export interface HeaderProps {
    // No props required
}

/**
 * Props for HeaderMobileMenu component
 */
export interface HeaderMobileMenuProps {
    navItems: NavItem[];
    socials: SocialObjects[];
}

// ============================================================================
// DOCS COMPONENT TYPES
// ============================================================================

/**
 * Sidebar entry with label information
 */
export interface SidebarEntryItem {
    slug: string;
    label: string;
    icon?: string;
}

/**
 * Props for SidebarEntry component
 */
export interface SidebarEntryProps {
    entry: SidebarEntryItem;
    currentSlug: string;
}

/**
 * Sidebar group with entries and subgroups
 */
export interface SidebarGroupItem {
    id: string;
    label: string;
    icon?: string;
    groups?: SidebarGroupItem[];
    entries?: SidebarEntryItem[];
}

/**
 * Props for SidebarGroup component
 */
export interface SidebarGroupProps {
    group: SidebarGroupItem;
    currentSlug: string;
    level?: number;
}

/**
 * Tab representing a top-level navigation group
 */
export interface Tab {
    id: string;
    label: string;
    icon?: string;
    group: SidebarGroupItem;
}

/**
 * Props for Sidebar component
 */
export interface SidebarProps {
    tabs: Tab[];
    showTabs: boolean;
    activeTab?: Tab;
    currentSlug: string;
}

/**
 * Heading information from document frontmatter/markdown
 */
export interface Heading {
    depth: number;
    text: string;
    id: string;
}

/**
 * Props for TableOfContents component
 */
export interface TableOfContentsProps {
    headings?: Heading[];
}

// ============================================================================
// MARKDOWN COMPONENT TYPES
// ============================================================================

/**
 * Props for MdxImage component - handles both string paths and ImageMetadata
 */
export interface MdxImageProps {
    src: string | ImageMetadata;
    alt?: string;
    class?: string;
    [key: string]: unknown;
}

/**
 * Props for MdxLink component - determines if link is external
 */
export interface MdxLinkProps {
    href?: string;
    class?: string;
    [key: string]: unknown;
}
