[tools]
python = "3.14"
prek = "latest"
node = "lts"
pnpm = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["python"]

[hooks]
enter = "bash ./scripts/enter_project.sh"

[env]
_.path = ['{{config_root}}/node_modules/.bin']
_.file = '.env'

[tasks.dev]
description = "Dev Mode"
run = "astro dev --host 0.0.0.0"

[tasks.dicon]
description = "Downloads an SVG from svgrepo and saves it to src/assets/icons/"
run = "bash ./scripts/download-icon.sh"

[tasks.lint]
description = "Run Biome checks"
run = "biome check ."

[tasks.lint-fix]
description = "Run Biome checks and apply safe fixes"
run = "biome check --write ."

[tasks.format]
description = "Format files with Biome"
run = "biome format --write ."

[tasks.biome-ci]
description = "Run Biome CI checks"
run = "biome ci ."
