[tools]
github-cli = "latest"
node = "lts"
pnpm = "latest"
prek = "latest"
rumdl = "latest"
uv = "latest"

[settings]
experimental = true

[hooks]
enter = "bash ./scripts/enter_project.sh"

[env]
_.file = '.env'                                # for sensitive data
_.path = ['{{config_root}}/node_modules/.bin']

[tasks.dev]
description = "Dev Mode"
run = "astro dev --host 0.0.0.0"

[tasks.dicon]
description = "Downloads an SVG from svgrepo and saves it to src/assets/icons/"
run = "bash ./scripts/download-icon.sh"

[tasks.biome]
description = "Run Biome checks and apply safe fixes"
run = "biome check --write . && biome format --write ."
