import type { HeadSEOProps } from "@/lib/types";
import type { CollectionEntry } from "astro:content";

// ============================================================================
// NAVIGATION TYPES - Documentation Navigation
// ============================================================================

/**
 * Sidebar entry representing a single documentation page
 */
export interface Entry {
    slug: string;
    label?: string;
    icon?: string;
    hidden?: boolean;
}

/**
 * Sidebar group containing entries and subgroups
 */
export interface Group {
    id: string;
    label: string;
    icon?: string;
    path?: string;
    tab?: boolean;
    autoGenerated?: boolean;
    groups?: Group[];
    entries?: Entry[];
}

/**
 * A top-level sidebar item can be either a Group or a bare Entry.
 * This allows mixing entries and groups in the configuration and preserving order.
 */
export type GroupOrEntry = Group | Entry;

/**
 * Sidebar group used by components may contain ordered children (mix of groups and entries)
 */
export interface SidebarGroupItem {
    id: string;
    label: string;
    icon?: string;
    groups?: SidebarGroupItem[];
    entries?: SidebarEntryItem[];
    children?: Array<SidebarGroupItem | SidebarEntryItem>;
}

/**
 * Sidebar configuration containing groups
 */
export interface Sidebar {
    groups: GroupOrEntry[];

    /** Optional configuration for the default tab shown when root docs exist */
    defaultTab?: {
        label?: string;
        icon?: string;
    };
}

/**
 * Mapping of content systems to their sidebar configuration
 */
export interface SidebarNavigation {
    [systemId: string]: Sidebar;
}

// ============================================================================
// LAYOUT COMPONENT TYPES
// ============================================================================

/**
 * Props for BaseLayout component
 */
export interface BaseLayoutProps extends Partial<HeadSEOProps> {
    fullWidth?: boolean;
}

/**
 * Props for DocsLayout component
 */
export interface DocsLayoutProps extends Partial<HeadSEOProps> {
    headings?: Heading[];
    frontmatter: CollectionEntry<any>;
    collection?: string;
}

// ============================================================================
// DOCS COMPONENT TYPES
// ============================================================================

/**
 * Props for DocIcon component - displays icon with fallback to document icon
 */
export interface DocIconProps {
    name?: string;
    class?: string;
    [key: string]: unknown;
}

/**
 * Sidebar entry with label information
 */
export interface SidebarEntryItem {
    slug: string;
    label: string;
    icon?: string;
}

/**
 * Props for SidebarEntry component
 */
export interface SidebarEntryProps {
    entry: SidebarEntryItem;
    currentSlug: string;
}

/**
 * Sidebar group with entries and subgroups
 */
export interface SidebarGroupItem {
    id: string;
    label: string;
    icon?: string;
    groups?: SidebarGroupItem[];
    entries?: SidebarEntryItem[];
}

/**
 * Props for SidebarGroup component
 */
export interface SidebarGroupProps {
    group: SidebarGroupItem;
    currentSlug: string;
    level?: number;
}

/**
 * Tab representing a top-level navigation group
 */
export interface Tab {
    id: string;
    label: string;
    icon?: string;
    group: SidebarGroupItem;
}

/**
 * Props for Sidebar component
 */
export interface SidebarProps {
    tabs: Tab[];
    showTabs: boolean;
    activeTab?: Tab;
    currentSlug: string;
}

/**
 * Heading information from document frontmatter/markdown
 */
export interface Heading {
    depth: number;
    text: string;
    id: string;
    slug?: string;
}

/**
 * Props for TableOfContents component
 */
export interface TableOfContentsProps {
    headings?: Heading[];
}

// ============================================================================
// MARKDOWN COMPONENT TYPES
// ============================================================================

/**
 * Props for MdxImage component - handles both string paths and ImageMetadata
 */
export interface MdxImageProps {
    src: string | ImageMetadata;
    alt?: string;
    class?: string;
    [key: string]: unknown;
}

/**
 * Props for MdxLink component - determines if link is external
 */
export interface MdxLinkProps {
    href?: string;
    class?: string;
    [key: string]: unknown;
}
