import setupImage from "@/assets/setup.png";
import type { Sidebar } from "@/lib/docs/types";
import type {
    HeaderFeatures,
    LocaleConfig,
    NavItem,
    SiteConfig,
    SocialObjects,
    TableOfContentsConfig,
} from "@/lib/types";

// ---------------------------------------------------------------------------
// System-wide configuration
// ---------------------------------------------------------------------------
export const LOCALE: LocaleConfig = {
    lang: "en",
};

export const SITE: SiteConfig = {
    website: "https://celestialdocs.hyperoot.dev",
    author: "Rajesh",
    repo: "https://github.com/HYP3R00T/CelestialDocs",
    title: "CelestialDocs",
    description: "Documentation template using Astro and Shadcn",
    image: setupImage,
    imageAlt: "Check out celestialdocs.hyperoot.dev",
    twitterHandle: "@HYP3R00T",
    defaultDocRedirect: "/docs/getting-started/introduction",
};

// ---------------------------------------------------------------------------
// Header-specific configuration
// ---------------------------------------------------------------------------
export const HEADER_FEATURES: HeaderFeatures = {
    starCountThreshold: 0,
    enableLayoutWidthToggle: true,
    enableGitHubButton: true,
};

export const HEADER_NAV_ITEMS: NavItem[] = [
    { href: "/docs", label: "Docs", special: true },
];

export const HEADER_SOCIAL_LINKS: SocialObjects[] = [
    {
        name: "github",
        href: "https://github.com/HYP3R00T/",
        linkTitle: `Checkout my GitHub profile`,
        active: true,
    }
];

// ---------------------------------------------------------------------------
// Sidebar navigation structure for docs content
// ---------------------------------------------------------------------------
export const SIDEBAR_NAVIGATION: Sidebar = {
    groups: [
        {
            id: "getting-started",
            label: "Getting Started",
            icon: "rocket",
            autoGenerated: true,
            entries: [
                { slug: "getting-started/introduction" },
                { slug: "getting-started/installation" },
            ],
        },
        {
            id: "guides",
            label: "Guides",
            icon: "book",
            autoGenerated: true,
            entries: [
                { slug: "guides/usage" },
            ],
            groups: [
                {
                    id: "guides/advanced",
                    label: "Advanced Topics",
                    path: "guides/advanced",
                    entries: [
                        { slug: "guides/advanced/patterns" },
                        { slug: "guides/advanced/anti-patterns" },
                    ],
                },
            ],
        },
        // Top-level bare entry (not grouped) to be rendered inline
        { slug: "quick-tour", label: "Quick Tour", icon: "sparkles" },
        {
            id: "components",
            label: "Components",
            icon: "puzzle",
            tab: true,
            path: "components",
            autoGenerated: true,
            entries: [
                { slug: "components/button" },
                { slug: "components/input" },
            ],
            groups: [
                {
                    id: "components/form",
                    label: "Form Controls",
                    icon: "form",
                    tab: true,
                    path: "components/form",
                    autoGenerated: true,
                    entries: [
                        { slug: "components/form/form" },
                        { slug: "components/form/validation" },
                    ],
                },
            ],
        },
        {
            id: "faq",
            label: "FAQ",
            icon: "help",
            // tab: true,
            path: "faq",
            autoGenerated: true,
        },
    ],
};

// ---------------------------------------------------------------------------
// Right-side table of contents configuration
// ---------------------------------------------------------------------------
export const TABLE_OF_CONTENTS: TableOfContentsConfig = {
    enableExtra: false,
};
