import setupImage from "@/assets/setup.png";
import type { SidebarNavigation } from "@/lib/docs/types";
import type {
    ContentConfig,
    HeaderFeatures,
    LocaleConfig,
    NavItem,
    SiteConfig,
    SocialObjects,
    TableOfContentsConfig,
} from "@/lib/types";

// ---------------------------------------------------------------------------
// System-wide configuration
// ---------------------------------------------------------------------------
export const LOCALE: LocaleConfig = {
    lang: "en",
};

export const CONTENT: ContentConfig = {
    // `systems` enables multiple documentation systems (e.g., docs, notes)
    // Add more entries here to register additional content systems.
    systems: [
        {
            id: "docs",
            dir: "content/docs",
            defaultDocRedirect: "/docs/1-start-here/what-is-celestialdocs",
            route: "/docs",
        }
    ],
};

export const SITE: SiteConfig = {
    website: "https://celestialdocs.hyperoot.dev",
    author: "Rajesh",
    repo: "https://github.com/HYP3R00T/CelestialDocs",
    title: "CelestialDocs",
    description: "Documentation template using Astro and Shadcn",
    image: setupImage,
    imageAlt: "Check out celestialdocs.hyperoot.dev",
    twitterHandle: "@HYP3R00T",
};


// ---------------------------------------------------------------------------
// Header-specific configuration
// ---------------------------------------------------------------------------
export const HEADER_FEATURES: HeaderFeatures = {
    starCountThreshold: 0,
    enableLayoutWidthToggle: true,
    enableGitHubButton: true,
};

export const HEADER_NAV_ITEMS: NavItem[] = [
    { href: "/docs", label: "Docs" },
];

export const HEADER_SOCIAL_LINKS: SocialObjects[] = [
    {
        name: "github",
        href: "https://github.com/HYP3R00T/",
        linkTitle: `Checkout my GitHub profile`,
        active: true,
    }
];

// ---------------------------------------------------------------------------
// Sidebar navigation structure for docs content
// ---------------------------------------------------------------------------
export const SIDEBAR_NAVIGATION: SidebarNavigation = {
    docs: {
        defaultTab: {
            label: "Learn",
            icon: "book",
        },
        groups: [
            // TAB 1: Start Here (Quick onboarding)
            {
                id: "start-here",
                label: "Start Here",
                icon: "🌟",
                tab: true,
                autoGenerated: true,
                entries: [
                    { slug: "1-start-here/what-is-celestialdocs" },
                    { slug: "1-start-here/your-first-page" },
                    { slug: "1-start-here/understanding-markdown" },
                ],
            },

            // TAB 2: Core Concepts (Foundation)
            {
                id: "core-concepts",
                label: "Core Concepts",
                icon: "💡",
                tab: true,
                autoGenerated: true,
                groups: [
                    {
                        id: "markdown-and-content",
                        label: "Markdown & Content",
                        icon: "📝",
                        autoGenerated: true,
                        entries: [
                            { slug: "2-core-concepts/frontmatter-explained" },
                            { slug: "2-core-concepts/what-is-an-entry" },
                            { slug: "2-core-concepts/what-is-a-group" },
                            { slug: "2-core-concepts/mdx-and-components" },
                            { slug: "2-core-concepts/content-structure" },
                        ],
                    },
                ],
            },

            // TAB 3: Configuration (How to configure)
            {
                id: "configuration",
                label: "Configuration",
                icon: "⚙️",
                tab: true,
                autoGenerated: true,
                groups: [
                    {
                        id: "config-basics",
                        label: "Basics",
                        icon: "🔧",
                        autoGenerated: true,
                        entries: [
                            { slug: "3-configuration/config-overview" },
                            { slug: "3-configuration/site-metadata" },
                            { slug: "3-configuration/header-navigation" },
                        ],
                    },
                    {
                        id: "multi-collections",
                        label: "Multiple Collections",
                        icon: "🔄",
                        autoGenerated: true,
                        entries: [
                            { slug: "3-configuration/content-systems" },
                        ],
                    },
                ],
            },

            // TAB 4: Sidebar Navigation (CRITICAL SECTION)
            {
                id: "sidebar-deep-dive",
                label: "Sidebar Navigation",
                icon: "📑",
                tab: true,
                autoGenerated: true,
                groups: [
                    {
                        id: "sidebar-fundamentals",
                        label: "Fundamentals",
                        icon: "📋",
                        autoGenerated: true,
                        entries: [
                            { slug: "4-sidebar-navigation/sidebar-overview" },
                            { slug: "4-sidebar-navigation/what-is-a-tab" },
                            { slug: "4-sidebar-navigation/icons-and-emojis" },
                            { slug: "4-sidebar-navigation/auto-generation" },
                            { slug: "4-sidebar-navigation/ordering-and-hidden" },
                        ],
                    },
                    {
                        id: "sidebar-examples",
                        label: "Examples",
                        icon: "💻",
                        autoGenerated: true,
                        entries: [
                            { slug: "4-sidebar-navigation/sidebar-config-examples" },
                        ],
                    },
                ],
            },

            // TAB 5: Features
            {
                id: "features",
                label: "Features",
                icon: "✨",
                tab: true,
                autoGenerated: true,
                entries: [
                    { slug: "5-features/theme-and-layout" },
                    { slug: "5-features/table-of-contents" },
                    { slug: "5-features/breadcrumbs" },
                    { slug: "5-features/source-button" },
                ],
            },

            // TAB 6: Common Patterns
            {
                id: "patterns",
                label: "Patterns",
                icon: "🎯",
                tab: true,
                autoGenerated: true,
                entries: [
                    { slug: "6-common-patterns/two-collection-layout" },
                    { slug: "6-common-patterns/custom-landing" },
                ],
            },

            // TAB 7: Help & Support
            {
                id: "help",
                label: "Help",
                icon: "❓",
                tab: true,
                autoGenerated: true,
                entries: [
                    { slug: "7-help/faq" },
                    { slug: "7-help/troubleshooting" },
                ],
            },
        ],
    },
};

// ---------------------------------------------------------------------------
// Right-side table of contents configuration
// ---------------------------------------------------------------------------
export const TABLE_OF_CONTENTS: TableOfContentsConfig = {
    enableExtra: false,
};
